[book]
authors = ["Rob Cobb"]
language = "en"
multilingual = false
src = "src"
title = "Web Application Development"

[build]
build-dir = "output"
create-missing = false
use-default-preprocessors = false
